Feature/ui
walimike/fast-food-fast pull request #1
Opened 2018-09-16 08:54 UTC by walimike

**This PR adds UI content for fast-food-fast app**
The UI pages can be viewed directly here; https://walimike.github.io/fast-food-fast/ 
 @joelethan, @KicaRonaldOkello, @jeanjoe, @malmike, @billkabanga please give me some feedback, thank you.

2018-09-16 10:18 UTC, Luleherll commented
i think you should remove the transparency on` user and admin`. the items can't be seen clearly

2018-09-17 07:18 UTC, jeanjoe requested changes

2018-09-17 07:18 UTC, jeanjoe commented on UI/adminhome.html
> +          <table>
Please use `<tr>` and `<td>` inside `<table>` and then you can add other HTML tags like`<p>`.

2018-09-17 07:22 UTC, walimike commented on UI/adminhome.html
> +          <table>
Oh okay, thank you

2018-09-17 07:42 UTC, jeanjoe requested changes

2018-09-17 07:42 UTC, jeanjoe commented on UI/signup.html
> +        <h1>Fast Food <span class="highlight">Fast</span><h1>
You did not close `<h1>` tag

2018-09-17 07:42 UTC, jeanjoe commented on UI/index.html
> +        <h1>Fast Food <span class="highlight">Fast</span><h1>
Close `<h1>` tag

2018-09-17 07:42 UTC, jeanjoe commented on UI/userhome.html
> +  <body>
You should not have `<body>` tag inside a `<div>`.  Body should always come first after `</head>`

2018-09-19 14:15 UTC, walimike commented
Merges UI commits to develop

2018-09-19 14:15 UTC, merged